[theme]
base = "light"
primaryColor = "#245C49"
backgroundColor = "#F7F8F4"
secondaryBackgroundColor = "#EEF1E9"
textColor = "#213C34"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
